name: test

# only run on pull requests targeting `master` branch
on:
  pull_request:
    branches:
    - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, eslint, and test
      run: |
        npm install
        npm run eslint
        npm test
      env:
        CI: true